@startuml container
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

' Container diagram showing overview of Seedcase
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user_contributor, "Data contributor")
Person(user_admin, "Project admin")
Person(user_owner, "Project owner")

System_Boundary(seedcase, "Seedcase Sprout") {
  Container(ui, "User interface", "HTML, CSS, JavaScript")
  Container(projects, "Project management", "Python, Django, SQLite",  $descr="Create projects, manage existing ones")
  Container(data, "Data management", "Python, Django", $descr="Run checks, process data, send to database")
  ' Authentication inside or outside?
  Container(login, "User login", "Python, Django")
  Container(users, "User management", "Python, Django, SQLite", $descr="Assign roles, add or remove users")
  
  ' Backend database setup
  ContainerDb(database_data, "Relational database for data", "Postgres/SQLite")
  ContainerDb(database_metadata, "Relational database for metadata", "SQLite")
  ContainerDb(file_storage, "File storage for raw data", "Filesystem")
}
' Authentication inside or outside?
' System_Ext(id_authentication, "User Authentication")

' Double spaces because PlantUML C4 is weird with rendering these text
Rel(user_contributor, login, "Input  data")
Rel(user_admin, login, "Manage  data  and  users")
Rel(user_owner, login, "Create  and  manage  users  and  data")
Rel(login, ui, "")
BiRel(ui, projects, "")
BiRel(projects, users, "")
BiRel(projects, data, "")

Rel(data, database_data, "")
Rel(data, database_metadata, "")
Rel(data, file_storage, "")

@enduml
