# fly.toml app configuration file generated for seedcase-sprout on 2024-01-09T18:05:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seedcase-sprout"
primary_region = "ams"
# Politely stop the process, rather than an abrupt close (default is SIGINT, signal interrupt).
kill_signal = "SIGTERM"
# Prevent the app from closing too early. Closes after 3 minutes.
kill_timeout = 180

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

# A volume is used to persist files between deployments. The volume was created with:
# fly volume create persistent_storage --region ams --count 1
# See https://fly.io/docs/reference/volumes/ for more information
# NOTE: this will only work if an app is running on one machine
[mounts]
  source="persistent_storage"
  destination="/code/persistent_storage"
