---
title: Grow structured, organized, and *usable* data
format:
  seedcase-theme-html:
    toc: false
page-layout: custom
section-divs: false
sidebar: false
about:
  id: hero-heading
  template: jolla
  image: "docs/images/home.svg"
  image-title: Image from Storyset.
  image-alt: Illustration of a woman interacting with digital files and folders, with database objects on the ground in front of her.
  image-shape: rectangle
  image-width: 25em
  links:
    - text: "Install Sprout"
      href: "https://sprout.seedcase-project.org/docs/guide/installation"
    - text: "Explore guide"
      href: "https://sprout.seedcase-project.org/docs/guide"
---

```{=html}
<style>
div.quarto-about-jolla {
  margin-top: 0%;
  margin-bottom: 0%;
}
</style>
```

:::: landing-page-block
::: {#hero-heading}
{{< include /docs/includes/_badges.qmd >}}
:::
::::

::::: hero-banner
:::: landing-page-block
::: hero-text
## Streamlined data management for every workflow

**Sprout** is at the backbone of the [**Seedcase
Project**](https://seedcase-project.org), offering a flexible solution
to structure and manage your data.

Sprout is a **Python package** with a flexible interface directed at
those whose task is to build up and organise data for a project or
research study, as well as those who want more control over
individual steps in the data processing and management workflow.

We designed this package mainly for computationally technical personnel,
such as data engineers or software developers. It's designed to be
easily extended and customized to fit your needs, within a framework
that ensures your data is structured, organized, and usable.
:::
::::
:::::

::: landing-page-block
## Want to contribute?

We would love your feedback or contributions! Head over to our [GitHub
repository](https://github.com/seedcase-project/seedcase-sprout) to
share your ideas or contribute code. Your input makes us better!

<!-- TODO: Add link to a guide on how to contribute in more detail -->
:::

:::: {.content-hidden when-format="pdf"}
::: landing-page-block
## Image by [Storyset](https://storyset.com/data) {.appendix}
:::
::::
