"""Migration to add polars_types to ColumnDataType."""
# Generated by Django 4.2.8 on 2024-02-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migration to add polars_types to ColumnDataType."""

    dependencies = [
        ("sprout", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="columndatatype",
            name="polars_types",
            field=models.TextField(default=""),
        ),
    ]
