# Generated by Django 4.2.8 on 2024-02-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprout', '0002_alter_columnmetadata_description'),
        ('sprout', '0002_columndatatype_polars_types'),
    ]

    operations = [
    ]
