@startuml user-flow-validation-table-completeness
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

title User Flow: Validation Check of Table Completeness

:...;
#palegreen:Initial table has been created;
'copied from user-flow.puml start
'validation table completeness start
   while (\nVALIDATION CHECK: Table Completeness\nSystem checks that table has all the required metadata\n) is (Validation failed)
    :System shows UI with table where
    missing fields are highlighted
    :User completes/edits table;
    if (System asks user if they want to save only or submit) then (Save only)
      :User clicks "Save Draft";
      end
    else (Save and Submit)
      :User clicks "Submit";
      label l
    endif
  end while (Validation successful)
  :System shows UI with table for user confirmation;
  while (User decides whether table is correct or needs editing) is (Incorrect table)
    :User clicks "Edit Table";
    :System shows UI with table
    :User edits table;
    :User clicks "Continue";
    goto l
   end while (Correct table)
   :User clicks "Submit";
  #palegreen:Systems confirms: "New Table added Successfully";
'validation table completeness end
'copied from user-flow.puml end
:...;

@enduml
