@startuml user-flow-prepare-to-upload-using-existing-table
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

title User Flow: Prepare to Upload using Existing Table

:User selects option to "Upload Data";
if (System shows data upload UI) then (Create New Table)
  :...;
'copied from user-flow.puml start
'prepare to upload using existing table start
else (Use Existing Table)
    :User selects\n"Use Existing Table";
    :System shows UI with existing tables
    to choose from and file upload;
    :User selects existing table and
    selects file to upload;
    :User clicks "Upload Data to Table";
endif
'prepare to upload using existing table end
'copied from user-flow.puml end
:System initialises data upload;
:...;

@enduml
