# Generated by Django 4.2.8 on 2024-01-18 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from app.models import ColumnDataType


def add_data_types(apps, schema_editor):
    ColumnDataType(display_name="Text", description="A text description").save()
    ColumnDataType(display_name="Numeric", description="A number").save()
    ColumnDataType(display_name="Yes/No", description="Yes or No").save()
    ColumnDataType(display_name="Integer", description="Whole number without decimals").save()
    ColumnDataType(display_name="Time", description="Date and time").save()


# Django expects a method for reverting add_data_types.
# We will do nothing because the ColumnDataType is deleted anyway
def add_data_types_reversed_dummy(apps, schema_editor):
    print("Types are deleted")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TableMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('original_file_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='modifier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('allow_missing_value', models.BooleanField()),
                ('allow_duplicate_value', models.BooleanField()),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.columndatatype')),
                ('table_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tablemetadata')),
            ],
        ),
        migrations.RunPython(add_data_types, add_data_types_reversed_dummy)
    ]
