# Generated by Django 4.2.8 on 2024-02-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columnmetadata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
