# Generated by Django 4.2.8 on 2024-02-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='columndatatype',
            name='pandas_type',
            field=models.TextField(default=object),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='columndatatype',
            name='python_type',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
    ]
