---
title: "Core Python functions"
callout-icon: false
callout-appearance: "minimal"
---

::: {.callout-important appearance="default" icon="true"}
We created this document mainly as a way to help us as a team all
understand and agree on what we're making and what needs to be worked
on. Which means that the descriptions and explanations of these
functions will likely change quite a bit and may even be deleted later
when they are no longer needed.
:::

Based on the [naming scheme](/docs/design/architecture/naming.qmd) and
the [Frictionless Data Package standard](https://datapackage.org), these
are the core external-facing functions in Sprout. See the
[Outputs](outputs.qmd) section for an overview and explanation of the
different outputs provided by Sprout.

There are some small differences between the naming scheme and the
functions described here:

1.  Whenever `view` is used, it is always for one object (either a
    package or a resource). Whenever `list` is used, it is always to
    show basic details of all existing objects of a given type (e.g.
    resources). Both `view` and `list` only ever show the information
    contained in the `datapackage.json` and never show actual data. We
    don't provide the ability for Sprout to show personally-identifiable
    data directly since it is [out of scope](index.qmd#goals) of Sprout
    and we want to minimise any security and privacy risks. Those with
    at least read access to the filesystem will still be able to see the
    data directly.
2.  `edit` only ever edits the `datapackage.json` which contains the
    properties/metadata of the package or resource(s) but never edits
    the data itself. If there is a need for updates to the data itself,
    the user can update it by uploading a new file with the updates (as
    long as the primary keys like participant ID and time of collection
    are the same). We don't provide access for users to directly edit
    the data because we want to limit security risks as well as to
    maintain privacy and legal compliance.
3.  `add` only ever adds more data to an existing data resource and does
    not add any new metadata to the `datapackage.json`. Since Sprout
    contains the full Frictionless Data specification, using `edit` is
    enough to make updates to the existing properties found in the
    `datapackage.json` file.

Nearly all functions have a `path` argument. Depending on what the
function does, the path object will be different. Use the `path_*()`
functions to get the correct path object for the specific function. It's
designed this way to make it more flexible to where individual packages
and resources are stored and to make it a bit easier to write tests for
the functions. For a similar reason, most of the functions output either
a `dict` Python object, a custom `Properties` dataclass, or a path
object to make them easier to test.

Several of the functions have an argument called `properties`. The
properties argument is a list of key-value pairs (as a JSON-style `dict`
object), built using the `Properties` object, that describes the package
and resource(s) in the package. This metadata is stored in the
`datapackage.json` file and follows the Frictionless Data specification.

::: {.callout-important appearance="default" icon="true"}
Functions shown in orange are not yet implemented while those in blue
are implemented.
:::

## Data package functions

::: {.callout-warning collapse="true"}
### `view_package_properties(path)`

This will show the information contained within the `datapackage.json`
file of a package for only the fields relevant to the package itself,
and only basic details of the resources within the package. Use
`path_properties()` to provide the correct path location. Outputs a JSON
object.
:::

::: {.callout-warning collapse="true"}
### `create_package_properties(properties)`

This is the first function to use to create a new data package. It
generates a template for the `datapackage.json` file where the user
needs to fill in required fields by providing the `properties` argument
using the helper `PackageProperties` class. Outputs a full Properties
object. Use `write_package_properties()` to store the properties to the
`datapackage.json` file.
:::

::: {.callout-warning collapse="true"}
### `build_readme_text(properties)`

Using a template, this will build a README file with the contents of the
properties object in a human-readable format. Outputs a text string. Use
`write_text()` to save the text to the `README.md` file.
:::

::: {.callout-note collapse="true"}
### `edit_package_properties(path, properties)`

See the help documentation with `help(edit_package_properties())` for
more details.
:::

::: {.callout-warning collapse="true"}
### `delete_package(path, confirm)`

Completely delete a specific package and all it's data resources.
Because this action would be permanent, the `confirm` argument would
default to `false` so that the user needs to explicitly provide `true`
to the function argument as confirmation. This is done to prevent
accidental deletion. Outputs `true` if the deletion was successful.
:::

::: {.callout-warning collapse="true"}
### `write_package_properties(properties, path)`

Writes the properties object containing package properties (with or
without resource properties) back to the `datapackage.json` file. The
`path` argument is the path to the folder that will have or currently
has the `datapackage.json` file. The `path` argument is to the existing
but empty folder or to a folder that doesn't exist but will be created
by this function. Will overwrite the `datapackage.json` file by default
if the file already exists. Returns the same path object as given in the
`path` argument.
:::

## Data resource functions

::: {.callout-note collapse="true"}
### `list_resources(path)`

This looks in one specific package's `datapackage.json` file and lists a
basic summary of all the data resources contained within the package.
The list would be basic information like resource ID, name, and
description. Use `path_resources()` to provide the correct path
location. Outputs a JSON object.
:::

::: {.callout-note collapse="true"}
### `view_resource(path, properties_path)`

Views the information on a package's specific resource that is contained
within the `datapackage.json` file. Use the `path_resource()` function
to provide the correct location for the `path` and `path_properties()`
for the `properties_path` argument. Outputs a JSON object.
:::

::: {.callout-note collapse="true"}
### `create_resource_structure(path)`

This is the first function to use to set up the structure for a data
resource. It creates the paths for a new data resource in a specific
(existing) package by creating the folder setup described in the
[Outputs](outputs.qmd) section. Use the `path_resources()` function to
provide the correct path location. It creates two paths: the
`resources/<id>/` path and the `resources/<id>/raw/` path. The output is
a list of these two path objects.

![Diagram showing the internal function flow of the
`create_resource_structure()`
function.](images/core/create-resource-structure.svg){#fig-create-resource-structure
fig-alt="A Plant UML schematic of the detailed code flow within the `create_resource_structure()` function."}
:::

::: {.callout-note collapse="true"}
### `create_resource_properties(path, properties)`

This function sets up and structures a new resource property by taking
the fields given in the `properties` argument to fill them and prepare
them to be added to the `datapackage.json` file. It must be given as a
`ResourceProperties` object following the Data Package specification.
The `path` argument provides the path to the resource `id` that the
properties are for; use `path_resource()` to provide the correct path
or use the output of `create_resource_structure()`. Outputs a
`ResourceProperties` object; use `write_resource_properties()` to save
the object to the `datapackage.json` file.

![Diagram showing the internal function flow of the
`create_resource_properties()`
function.](images/core/create-resource-properties.svg){#fig-create-resource-properties
fig-alt="A Plant UML schematic of the detailed code flow within the `create_resource_properties()` function."}
:::

::: {.callout-note collapse="true"}
### `write_resource_data_to_raw(path, data_path)`

Copy the file from `data_path` over into the resource location given by
`path`. This will compress the file and use a timestamped, unique file
name to store it as a backup. See the explanation of this file in the
[Outputs](outputs.qmd) section. Use `path_resource_raw()` to provide the
correct `path` location. Copies and compresses the file, and outputs the
path object of the created file.

![Diagram showing the internal function flow of the
`write_resource_data_to_raw()`
function.](images/core/write-resource-data-to-raw.svg){#fig-write-resource-data-to-raw
fig-alt="A Plant UML schematic of the detailed code flow within the `write_resource_data_to_raw()` function."}
:::

::: {.callout-note collapse="true"}
### `write_resource_parquet(raw_files, path)`

This function takes the files provided by `raw_files` and merges them
into a `data.parquet` file provided by `path`. Use
`path_resource_data()` to provide the correct path location for `path`
and `path_resource_raw_files()` for the `raw_files` argument. Outputs
the path object of the created file.
:::

::: {.callout-note collapse="true"}
### `edit_resource_properties(path, properties)`

Edit the properties of a resource in a package. The `properties`
argument must be a JSON object that follows the Frictionless Data
specification. Use the `path_properties()` function to provide the
correct path location. Outputs a JSON object only; use
`write_resource_properties()` to save the JSON object to the
`datapackage.json` file.
:::

::: {.callout-note collapse="true"}
### `delete_resource_raw_file(path, confirm)`

Use this to delete a raw file in the `raw/` folder of a resource. This
is useful if the file is no longer needed or if it is incorrect or had
an issue during the time when a user first added the file to a resource.
Use `path_resource_raw_files()` to select which file to delete from the
list of files found. Will only delete one file. The `confirm` argument
defaults to `false` so that the user needs to explicitly provide `true`
to the function argument as confirmation. This is done to prevent
accidental deletion. Outputs `true` if the deletion was successful.
:::

::: {.callout-note collapse="true"}
### `delete_resource_data(path, confirm)`

Delete all data (Parquet) and raw data of a specific
resource. Use `path_resource_raw()` to provide the correct path
location. The `confirm` argument defaults to `false` so that the user
needs to explicitly provide `true` to the function argument as
confirmation. This is done to prevent accidental deletion. Outputs
`true` if the deletion was successful. Use
`delete_resource_properties()` to delete the the associated
properties/metadata for the resource.
:::

::: {.callout-note collapse="true"}
### `delete_resource_properties(path, confirm)`

Deletes all properties for a resource within the `datapackage.json`
file. Use `path_properties()` to provide the correct location for
`path`. The `confirm` argument defaults to `false` so that the user
needs to explicitly provide `true` to the function argument as
confirmation. This is done to prevent accidental deletion. Outputs
`true` if the deletion was successful.
:::

::: {.callout-note collapse="true"}
### `write_resource_properties(properties, path)`

Use to write the resource JSON object back to the `datapackage.json`
file. This function validates whether the JSON object follows the Data
Package resource specification. The `properties` argument must be given
as a `ResourceProperties` object following the Data Package specification.
The `path` argument is the location of the `datapackage.json` file. Use
the `path_properties()` function to provide this path to the correct
location. Returns the same path object as given in the `path` argument.

![Diagram showing the internal function flow of the
`write_resource_properties()`
function.](images/core/write-resource-properties.svg){#fig-write-resource-properties
fig-alt="A Plant UML schematic of the detailed code flow within the `write_resource_properties()` function."}
:::

::: {.callout-note collapse="true"}
### `extract_resource_properties(path, data_path)`

This takes the data found at the `data_path` location and creates a JSON
object following the Frictionless Data standard. Internally it uses the
frictionless Python package to guess and fill in some of the property
fields required by the Frictionless Data resource specification. This
function is often followed by `edit_resource_properties()` to fill in
any remaining missing fields and then the `verify_resource_properties()`
function. Usually, you use either this function or the
`create_resource_properties()` function to create the resource
properties for the specific data resource given. The `path` argument
points to the resource `id` folder; use `path_resource()` to help give
the correct path. Outputs a JSON object. Use
`write_resource_properties()` to save the JSON object to the
`datapackage.json` file.

![Diagram showing the internal function flow of the
`extract_resource_properties()`
function.](images/core/extract-resource-properties.svg){#fig-extract-resource-properties
fig-alt="A Plant UML schematic of the detailed code flow within the `extract_resource_properties()` function."}
:::

## Path functions

-   Nearly all the below `path_*()` functions use `path_sprout_global()`
    internally to get the global path as well as `package_id` and/or
    `resource_id` to complete the correct path for the specific
    package/resource.
-   All of these functions output a path object.
-   The paths returned by all of these functions are paths that exist,
    so all include a `verify_is_dir()` or `verify_is_file()` check.
-   If the wrong `package_id` or `resource_id` is given, an error
    message will include a list of all the actual `package_id` at the
    `path_sprout_global()` location or all actual `resource_id` for a
    specific package.

::: {.callout-note collapse="true"}
### `path_*()` diagram

![Diagram showing the internal function flow of most of the `path_*()`
functions.](images/core/path-generic.svg){#fig-path-generic
fig-alt="A Plant UML schematic of the detailed code flow within a typical `path_*()` function."}
:::

::: {.callout-note collapse="true"}
### `path_resources(package_id)`

Creates the absolute path to the package's resources directory.

#### Example usage

``` python
print(path_resources(1))
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout/packages/1/resources')]
```
:::

::: {.callout-note collapse="true"}
### `path_resource(package_id, resource_id)`

Creates the absolute path to a specific resource directory within a
package.

#### Example usage

``` python
print(path_resource(1, 2))
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout/packages/1/resources/2')]
```
:::

::: {.callout-note collapse="true"}
### `path_resource_raw(package_id, resource_id)`

Creates the absolute path to a resource's raw data directory within a
package.

#### Example usage

``` python
print(path_resource_raw(4, 2))
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout/packages/4/resources/2/raw')]
```
:::

::: {.callout-note collapse="true"}
### `path_resource_raw_files(package_id, resource_id)`

Creates a list of absolute paths to all the raw data files within a
resource's raw data directory within a package.

#### Example usage

``` python
print(path_resource_raw_files(4, 2))
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout/packages/4/resources/2/raw/2024-05-01T12:00:00Z-***.csv.gz')]
```
:::

::: {.callout-note collapse="true"}
### `path_resource_data(package_id, resource_id)`

Creates the absolute path to a resource's Parquet data file in a
package. Internally also has a `verify_is_file()` check.

#### Example usage

``` python
print(path_resource_data(4, 2))
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout/packages/4/resources/2/data.parquet')]
```
:::

## Properties dataclasses

These dataclasses contain an explicit, structured set of official
properties defined within a data package. The main purpose of these is
to allow us to pass structured properties objects between functions.
They also enable users to create valid properties objects more easily
and get an overview of optional and required class fields.

::: {.callout-note collapse="true"}
### `PackageProperties`

See the help documentation with `help(PackageProperties())` for more
details on the properties.
:::

## Properties functions

::: {.callout-warning collapse="true"}
### `read_properties(path)`

Reads the `datapackage.json` file, checks that is correct, and then
outputs a `PackageProperties` object.
:::

::: {.callout-warning collapse="true"}
### `view_properties(path)`

Reads the `datapackage.json` file, checks that is correct, and then
outputs a human-readable version of the properties as a string.
:::


::: {.callout-note collapse="true"}
### `path_properties(package_id)`

Creates the absolute path to the package's properties `datapackage.json`
file. Internally also has a `verify_is_file()` check.

#### Example usage

``` python
print(path_properties(6))
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout/packages/6/datapackage.json')]
```
:::

::: {.callout-note collapse="true"}
### `path_packages()`

Creates an absolute path to the directory that has or will have all the
data packages.

#### Example usage

``` python
print(path_packages())
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout/packages')]
```
:::

::: {.callout-note collapse="true"}
### `path_package(package_id)`

Creates the absolute path to the specific package folder.

#### Example usage

``` python
print(path_package(10))
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout/packages/10')]
```
:::

::: {.callout-note collapse="true"}
### `path_sprout_global()`

If the `SPROUT_GLOBAL` environment variable isn't provided, this
function will return the default path to where data packages will be
stored. The default locations are dependent on the operating system.
This function also creates the necessary directory if it doesn't exist.

![Diagram showing the internal function flow of the
`path_sprout_global()`
function.](images/core/path-sprout-global.svg){#fig-path-sprout-global
fig-alt="A Plant UML schematic of the detailed code flow within the `path_sprout_global()` function."}

#### Example usage

``` python
print(path_sprout_global())
```

<!-- TODO: This output will be autogenerated, so it can be wrong for now. -->

```
[PosixPath('~/.sprout')]
```

## Helper functions

::: {.callout-note collapse="true"}
### `list_files(path)`

List all files in a directory. Outputs a list of path objects.
:::

::: {.callout-note collapse="true"}
### `pretty_json(json)`

Create a prettier, human readable version of a JSON object.
:::

## Observational unit level functions

Observational unit is the level of detail on the entity (e.g. human,
animal, event) that the data was collected on. Example would be: A
person in a research study who came to the clinic in May 2024 to have
their blood collected and to fill out a survey.

::: {.callout-note collapse="true"}
### `delete_participant_data()`

TODO.
:::
