# Data Types in Use in Seedcase Sprout

When defining a table before upload of data the data types will be chosen from a pre-defined list of data types. These will be a subset of the data types that are available no matter which database we chose to work with.

## Main Data Types

The primary data types in most databases are text, numbers, dates and some form of yes/no (boolean) option.  We expect that this first iteration of Seedcase Sprout will be able to handle one or two of each of those, as well as some that are more machine-readable.

### Text

Raw text without any form of manipulation is one of the primary types of data Seedcase Sprout is able to store. The precise name varies depending on the database system, and it may be referred to as `Char`, `Varchar`, `nVarchar`, or `Text`. In most systems, more than one variation will be in use, all dependent on what data is expected. 

All variations of `Char` will have an option of limiting the number of characters that it is possible to store. This was especially crucial when disk space was at a premium and can still be used as a blunt form of validation of data being saved to a table. For instance, if the field is limited to 2 characters, you can't save the full name of a US state.

#### Choice, Naming, and Description in Seedcase Sprout

We will be using the Varchar without a limit at this point in time as Text is not a standard SQL type at present.  

|Name used in user interfaces |Description |
| --- | ------ |
| Text  | This is a text field without a limit on how much text can be stored in the field. Please see our documentation on the Seedcase website for further information.  |

<!-- TODO Add hyperlink to documentation when it's done -->

### Numbers

There are several options when it comes to dealing with storing numbers in a database. The most basic is `Integer`, which stores whole, i.e., non-decimal, numbers (both positive and negative). This data type is typically used where a decimal number doesn't make sense (e.g., when you are counting people, you can't have half a person). Often though, it is important to be able to record a decimal number, which will allow for greater precision. Decimals are often used when storing, for instance, measurements or lab results. 

The choice of number format will also in some instances allow for the database to enforce data quality, by rejecting data at upload if it doesn't conform to type. E.g., if height is stored as integers in cm, a reading in meters like 1.69 won't be allowed.

#### Choice, Naming, and Description in Seedcase Sprout

We offer two options for number formats, the `integer` for whole numbers and `double precision` (or `float`), for decimal numbers.

|Name used in user interfaces |Description  |
| --- | ----- |
| Whole number   | Also known as Integer. This is a number field which will only allow whole numbers to be stored. Pick this option if you want to store whole numbers (like postcode, number of people in a household, or height in cm), not if you want to store things like lab results. Please see our documentation on the Seedcase website for further information. |
| Decimal number | Also known as Float or Double Precision. This is a number field which will store decimal numbers. Pick this option if you want to store things like lab results, or height in meters. You should look at Whole number if you want to store things like postcodes. Please see our documentation on the Seedcase website for further information. |

<!-- TODO Add hyperlink to documentation when it's done -->

### Date and Time

Date and/or time can be stored in many ways in a database system. The most common are `date`, `time`, and `datetime`. There is also a choice to be made with regards to time zones and whether or not a system should be able to deal with data coming from around the world. We do not expect Seedcase to be used across time zones, so we have made the choice to not handle time zones.

#### Choice, Naming, and Description in Seedcase Sprout

|Name used in user interface |Description |
| --- | ----- |
| Date  | The date value will be stored as yyyy-mm-dd, should you need to store time alongside the date this can either be done separately (Time) or in the same field, which would mean that you need to chose the 'Date and Time' data type. Please see our documentation on the Seedcase website for further information. |
| Time  | The time value will be stored as hh:mm:ss.  Please see our documentation on the Seedcase website for further information.|
| Date and Time  |  Also known as DateTime or Timestamp. The value will be stored as yyyy-mm-dd hh:mm:ss. If you only need to store a date then look at the Date data type, likewise if you need to only store a time then look at the data type Time.  Please see our documentation on the Seedcase website for further information.|

<!-- TODO Add hyperlink to documentation when it's done -->

### True/False, Yes/No, Boolean

A standard data type in any system is the option of a boolean value, which can represent a set of either/or options. This could be yes/no or true/false, the values stored in the system will typically be 0 and 1 (or -1 and 0), the interpretation of these is up to the individual data user.

#### Choice, Naming, and Description in Seedcase Sprout

|Name used in user interface |Description |
| --- | ----- |
| True/False  | Also known as Yes/No or Boolean. This is the option to pick if you have data that falls into the either/or category, it will normally be stored as 0/1 or True/False. Should you need to store the actual words of 'Yes' and 'No' then you should look at the data type Text. Please see our documentation on the Seedcase website for further information. |

<!-- TODO Add hyperlink to documentation when it's done -->

### JSON

JSON is a language for organizing and sharing data between computers. It is easy for both humans and computers to read, making it a popular choice for exchanging information on the internet. Many database systems offers a `JSON` data type which will to some extent check that the text being uploaded is formatted in the correct way. This will offer a user a way of doing data quality control during upload to the database, minimising problems later on.

#### Choice, Naming, and Description in Seedcase Sprout

|Name used in user interface |Description |
| --- | ----- |
| JSON | This is a specialised data type which will check that the JSON data is correctly formatted on upload. If you do not wish to have such a check carried out then chose Text as the data type, even if you are uploading JSON data. Please see our documentation on the Seedcase website for further information. |

<!-- TODO Add hyperlink to documentation when it's done -->

