---
title: Use Cases
---

{{< include ../_wip.qmd >}}

The users and their associated use cases are:

1.  **Users inputting data** into the Data Resource, e.g., authorized
    centers and researchers. The use cases are:
    1.  Authorized centers (GPs and hospitals) upload standardized and
        routine data through the data entry web portal.
    2.  Authorized researchers upload generated data from completed data
        projects. Non-standardized data is either manually processed and
        cleaned before entering into the database or uploaded in its raw
        format and processed with a plugin specific to that data.
2.  **Users who are administrators and data controllers** of the Data
    Resource. Use cases are:
    1.  Initial upload of data that includes setting up tables and allocating space in the raw data file storage. 
    2.  Approve and authorize researchers to access the web portal for
        data requests and to manage current authorized researchers.
    3.  Manage collection centers' access and authorization.
    4.  Manage or handle potential issues with the data itself, through
        direct access to the data storage.
