@startuml runtime-login-sequence
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

' TODO: Need to upate this

title Login and Authentication Sequence of a Registered User

participant "User" as u
participant "Frontend" as f
participant "API" as api
participant "Backend" as db

u -> f --: Enter login information
f -> api --: Send login request
api -> db ++: Check permissions level
db --> api --: Send permissions level
api --> u --: Show permission-dependent content
@enduml
