@startuml create-resource-structure
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

state "Input" as input {
  input : - `path_*()` functions assist\n  with giving correct paths
' Arguments -----
  path : - Path to resources\n  folder in a package
}

state "Output" as output {
  output : - The package parent folder is shown as /
  output : - Output: list two paths, the resource path\n  and the resource raw path
  state "/resources/<id>/" as folder_id
  folder_id : Folder with assigned ID (e.g. '1')

  state "/resources/<id>/raw/" as folder_raw
  folder_raw : Raw folder with assigned ID (e.g. '1')
  folder_id --[hidden]> folder_raw
}

state "create_resource_structure()" as crs {
  crs : - Required argument: path

  state arg <<entryPoint>>
  input --> arg

  state "verify_is_dir()" as vid
  vid : - Required arg: path
  vid : - Output: path or Error
  arg --> vid

  state "get_ids()" as gi
  gi : - Required arg: path to\n  resources folder
  gi : - Output: list of existing\n  IDs (or the empty list)
  vid --> gi

  state "create_next_id()" as cni
  cni : - Required arg: list of existing IDs
  cni : - Output: ID
  gi --> cni

  state "create_id_path()" as cip
  cip : - Required args: path to resources folder\n  and ID to assign for folder
  cip : - Output: path to directory for new resource
  cni --> cip
  arg --> cip

  state "create_resource_raw_path()" as crrp
  crrp : - Required arg: path to resource ID
  crrp : - Output: path to raw folder
  cip --> crrp

  state "create_dirs()" as cd
  cd : - Required arg: list of paths of\n  directories to create
  cd : - Output: list of paths of created\n  directories
  cip --> cd
  crrp --> cd

  state return <<exitPoint>>
  cd --> return
  return --> output
}

@enduml
