@startuml create-resource-properties
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

state "Input" as input {
  input : - `path_*()` functions assist with giving correct paths
' Arguments -----
  path : - Path to resource <id> folder
  properties: - JSON object of the resource\n  following the Data Package spec
}

state "Output" as output {
  state "JSON" as json_output
  json_output : - JSON object of the resource following\n  the Data Package spec
  json_output : - Use `write_resource_properties()` to\n  save back to `datapackage.json`
}

state "create_resource_properties()" as crp {
  crp : - Required arg: path and properties object

  state arg_path <<entryPoint>>
  state arg_properties <<entryPoint>>

  path --> arg_path
  properties --> arg_properties

  state "check_is_dir()" as cid
  cid : - Required arg: path
  cid : - Output: path or Error
  arg_path --> cid : path object

  state "create_relative_resource_data_path()" as crrdp
  crrdp : - Required arg: absolute path from input
  crrdp : - Output: relative path\n  (e.g. `resources/1/data.parquet`)
  cid --> crrdp : path object

  state "check_resource_properties()" as chrp
  chrp : - Required arg: properties
  chrp : - Output: JSON or Error
  chrp : - Checks against spec
  arg_properties --> chrp : JSON object

  state "edit_property_field()" as epf
  epf : - Required args: properties, field, value
  epf : - Output: JSON
  crrdp --> epf : Update `path`\nproperty
  chrp --> epf : JSON object

  state "return" <<exitPoint>>
  epf --> return : JSON object
  return --> output
}
@enduml
