@startuml path-sprout-root
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

state "path_sprout_root()" as prs {

  state "get_root_envvar()" as gre
  gre : - If user sets the `SPROUT_ROOT`\n  environment variable

  state condition <<choice>>
  gre --> condition : path or none

  state "create_root_path()" as crp
  crp : - Uses `platformdirs` package\n  internally
  crp : - Ends with `sprout/`
  condition --> crp : env var\nnot found

  state select <<join>>
  crp --> select : path object
  condition --> select : path object, if\nenv var found

  state return <<exitPoint>>
  select --> return : path object
}

@enduml
