@startuml path-generic
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

state "path_*()" as pr {
  pr : - Required arg: package_id and/or resource_id
  pr : - Gets path for various package directories
  pr : - Almost all `path_*` type functions use this flow.

  state args <<entryPoint>>

  state "path_sprout_root()" as psr
  psr : - Output: path

  state "pathlib.Path()" as path
  path : - Required args: fstring in form of\n  `f"{root}/packages/{package_id}/..."`
  psr --> path : path object
  args --> path : integer

  state "verify_is_dir()" as vid
  vid : - Required arg: path
  vid : - Output: path or Error
  path --> vid

  state return <<exitPoint>>
  vid --> return : path object
}

@enduml
