@startuml write-package-properties
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

state "Input" as input {
  input: - Use `path_*()` functions to help\ncreate correct paths
' Arguments -----
  properties : - Properties objects in JSON format
  path : - Path to where properties is stored
}

state "Output" as output {
  output : - The package parent folder is shown as /
  state "/packages/<id>/datapackage.json" as properties_file
}

state "write_package_properties()" as wpp {
  wpp : - Required arg: properties and path

  state arg_path <<entryPoint>>
  state arg_properties <<entryPoint>>
  properties --> arg_properties
  path --> arg_path

  state "verify_package_properties()" as vpp
  vpp : - Required arg: properties
  vpp : - Output: JSON or Error
  vpp : - Checks that all fields\n  and values match spec
  vpp : - Checks that required\n  fields are present
  arg_properties --> vpp

  state "write_json()" as wj
  wj : - Required arg: json_object and path
  wj : - Output: path to created file
  vpp --> wj : JSON object
  arg_path --> wj : path object

  state return <<exitPoint>>
  wj --> return : path object
  return --> output
}

@enduml
