@startuml edit-package-properties
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

state "Input" as input {
  input : - `path_*()` functions assist with giving correct paths
' Arguments -----
  path : - Path to `datapackage.json` file\n  in the package `<id>` folder
  path : - User may or may not have directly\n  edited the JSON file
  properties: - JSON object of the package\n  following the Data Package spec
}

state "Output" as output {
  state "JSON" as json_output
  json_output : - JSON object of the package following\n  the Data Package spec
  json_output : - Use `write_package_properties()` to\n  save back to `datapackage.json`
}

state "edit_package_properties()" as cps {
  cps : - Required arg: path and properties
  cps : - Takes the current properties file and updates\n  the properties with the given fields

  state arg_path <<entryPoint>>
  state arg_properties <<entryPoint>>

  path --> arg_path : path object
  properties --> arg_properties : JSON object

  state "verify_is_file()" as vif
  vif : - Required arg: path
  vif : - Output: path or Error
  arg_path --> vif

  state "verify_package_properties()" as vpp
  vpp : - Required arg: properties
  vpp : - Output: JSON or Error
  vpp : - Checks that all fields\n  and values match spec
  vpp : - Checks that required\n  fields are present
  arg_properties --> vpp

  state "read_properties()" as rp
  rp : - Required arg: path
  rp : - Output: JSON
  vif --> rp : path object

  state "join_properties()" as jp
  jp : - Required args: current_properties\n  and new_properties
  jp : - Output: JSON
  jp : - New properties overwrite old ones
  rp --> jp : JSON object
  vpp --> jp : JSON object

  state "return" <<exitPoint>>
  jp --> return : JSON object
  return --> output
}

@enduml
