@startuml component-api-and-auth
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' C4 Component diagram for the API and Authentication modules

Container(auth, "Authentication") {
  Component(user_info, "Information on users", $descr="Metadata on registered users of the Data Resource")
}
Container(ui, "Web Interface")
Container(bee, "Backend Environment")

Container_Boundary(management, "User and Data Management (API)") {
  ' Variable metadata
  Component(get_metadata, "Request to view metadata", $descr="")
  Component(post_update_metadata, "Request to update metadata", $descr="")

  ' Data changelog
  Component(get_changelog, "", $descr="")
  Component(post_update_changelog, "", $descr="")

  ' Upload data
  Component(post_update_data_to_db, "", $descr="")
  Component(post_update_data_raw, "", $descr="")
  Component(process_data_raw_to_db, "", $descr="")
  Component(get_data, "", $descr="")

  ' Admin and data management
  Component(create_db_table, "", $descr="")
  Component(post_db_table, "", $descr="")

  ' Quality Control
  'Component(qc_general, "", $descr="")
  'Component(qc_plugins, "", $descr="")
}

Rel(management, auth, "Authenticate access")
Rel(ui, management, "Send and receive")

Rel(get_metadata, bee, "Get request")
Rel(get_changelog, bee, "Get request")

Rel(bee, get_data, "")

Rel(auth, post_update_metadata, "")
Rel(auth, post_update_changelog, "")
Rel(auth, post_update_data_to_db, "")
Rel(auth, post_update_data_raw, "")
Rel(post_update_data_raw, process_data_raw_to_db, "")

@enduml
