@startuml 
' Component diagram for the Seedcase product - Backend: File Storage
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(bee, "Backend Environment")
Container(management, "User and Data Management Layer")
Container(auth, "Authentication")
Container(auth, "Authentication") {
  Component(user_info, "Information on users", $descr="Metadata on registered users of the Data Resource")
}

Container_Boundary(ui, "Web Interface") {
  Container_Boundary(web, "Public web interface") {
    Component(page_landing, "Landing page", $descr="Welcome and overview page that directs users to other pages")
    Component(page_login, "Login page", $descr="To give authorized users access to specific pages in the Data Resource")
  }
  Container_Boundary(web_admin, "Internal web interface") {
    ' Admin
    Component(page_data_admin, "Data admin page", $descr="Management of data within the Data Resource, such as adding a new table")
    Component(page_data_qc, "Data quality control details page", $descr="Reports on basic quality and validation of data")

    ' Data entry
    Component(page_data_upload, "Data entry and upload page", $descr="Adding new or updating existing data in the Data Resource")
  }
}

' Logged in users
BiRel(page_login, user_info, "Retrieve user permissions")

Rel(page_login, page_data_upload, "Access with data entry permissions")
Rel(page_login, page_data_admin, "Access with admin permissions")
Rel(page_login, page_data_qc, "Access with admin permissions")

' Accessing backend
BiRel(web_admin, management, "Send and receive details")
BiRel(bee, management, "Store and retrieve data/metadata")

Lay_D(ui, management)
Lay_R(management, bee)

@enduml
