@startuml component-ui
!theme C4_green from <C4/themes>
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' C4 Component diagram for the user interface

Container(management, "Downstream management")
Container(auth, "Authentication")

Container_Boundary(ui, "Web interface") {
  Component(page_login, "Login page", $descr="To give authorized users access to specific pages of a project")

  Component(page_project_create, "Create new project page", $descr="Create a new project to store data")
  Component(page_projects_list, "List of all projects", $descr="Show all existing projects")

  ' Admin

  Component(page_metadata_list, "List all data tables", $descr="Show all tables that contain data in the project")
  Component(page_metadata_create, "Data creation page", $descr="Create space for data to be stored, including adding metadata")
  Component(page_metadata_update, "Update metadata page", $descr="Make edits to existing metadata in the project")

  Component(page_data_update, "Add data to existing data", $descr="Add new or update existing data in the project")

  Component(page_user_admin, "User admin page", $descr="Manage users within the project")

  Component(page_data_qc, "Data quality control details page", $descr="Reports on basic quality and validation of data")
}

Rel(page_project_create, auth, "Assign  user  as  owner")

BiRel(page_login, auth, "Retrieve  user  permissions")
Rel(page_login, page_project_create, "Anyone")
Rel(page_login, page_projects_list, "Any  project  user")

Rel(page_projects_list, page_metadata_list, "Any  project  user")
Rel(page_projects_list, page_metadata_create, "Owner  and  admin")
Rel(page_projects_list, page_user_admin, "Any  project  user")
Rel(page_user_admin, auth, "Add  or  update  roles")

Rel(page_metadata_list, page_metadata_update, "Owner  and  admin")
Rel(page_metadata_list, page_data_qc, "Owner  and  admin")
Rel(page_metadata_list, page_data_update, "Any  project  user")

' Accessing backend
BiRel(ui, management, "Send  and  receive  details")

@enduml
