@startuml component-backend
!theme C4_green from <C4/themes>
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

' C4 Component diagram for backend database and file storage.

Container(management, "Management containers")

Container_Boundary(bee, "Data and metadata storage") {
  Container_Boundary(rdb_metadata, "Relational database for metadata") {
    Component(changelog, "Changelog of data and metadata", $descr="Listing changes made to the data and metadata")
    Component(metadata, "Metadata on data", $descr="Information about the data, like data types, column names, column descriptions, and description of data collection or generation procedure")
  }
  Component(users, "Database for user details", $descr="Details about user, roles, and connected projects")
  Component(projects, "Database for project details", $descr="Details about projects, like a summary list of data and users within the project")
  Container_Boundary(data_storage, "Storage for project data") {
    Component(data, "Relational database for data", $descr="Data uploaded for project entered into database")
    Component(raw_file, "File storage", $descr="A copy of the raw data that is saved to the database")
  }
}

Lay_Right(rdb_metadata, users)
Lay_Right(data_storage, projects)
Lay_Down(rdb_metadata, data_storage)

Rel(management, data_storage, "Write")

BiRel(management, projects, "Read  and  write")
BiRel(management, users, "Read  and  write")

BiRel(management, metadata, "Read  and  write")
BiRel(management, changelog, "Auto-generated")

@enduml
