@startuml context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

' C4 Context diagram

Person(user_data_input, "Data input")
Person(user_admin, "Admin", "Data controllers or data managers")

System(ui, "Data Resource structured by Seedcase Sprout")

Rel(user_data_input, ui, "Uploads data")
Rel(user_admin, ui, "Manages issues and data inputs")
@enduml
