@startuml data-upload-sequence

title Data Upload from Existing Schema
' User uploads data to existing data schema

'Question: Will this process be identical for initial and subsequent uploads? 
'I'm guessing not? Should we create a new sequence diagram for that?

participant "User" as u
participant "Front end" as f
participant "API" as api
participant "Backend" as b

u -> f: User selects option to "Upload data"
f -> u: System shows data entry UI
u -> f: User selects "Upload Data based on Existing Schema"\nand selects existing schema from dropdown and file to\nupload (csv).
f -> api: System transfers data and ID of selected schema
api -> b: System transfers ID of selected schema 
b -> api: System retrieves existing schema
api -> api: System validates\nby comparing data to schema

group Validation error (data does not match schema)
    api --> f: System sends back error "Upload failed"\n with information on where they don't match.
    note right of f
        This could be a system endpoint.
        Alternatively, user could be given the option to
        "Cancel Upload" or "Correct Upload(?)"
    end note
end
group Validation success (data matches schema)
    api -> b: System posts data upload with "Completed" flag
    b -> b : System creates record\nand saves data upload
    b -> api: System confirms data upload
    api -> f: System retrieves confirmation
    f -> u: System displays confirmation
end

@enduml
