@startuml function-flow
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main
skinparam StateFontColor black
skinparam StateFontSize 18
skinparam StateFontName Fira Code

state "Projects functionality" as group_projects {
  state projects 
  projects : - could be a separate page 
  projects : - list all projects
  projects : - select a project
  projects : - create new project
  projects : - update project
  projects : - delete project

  state "<&plus> projects create" as projects_create
  projects_create : - could be a separate page 
  projects_create : - write a name
  projects_create : - write a description
  projects_create : - (optional) add users
  projects_create : - (optional) set user permissions
  projects_create : - link to view newly created project

  state "<&magnifying-glass> projects <id>" as projects_id
  projects_id : - could be a separate page 
  projects_id : - view project landing page
  projects_id : - view description
  projects_id : - view users
  projects_id : - link to (meta)data

  state "<&pencil> projects <id> update" as projects_id_update
  projects_id_update : - could be a separate page 
  projects_id_update : - update name
  projects_id_update : - update description
  projects_id_update : - update users?

  state "<&trash> projects <id> delete" as projects_id_delete
  projects_id_delete : - could be a button only
  projects_id_delete : - delete all contents of project 
}

state "Metadata functionality" as group_metadata {
  state "<&magnifying-glass> projects <id> metadata" as projects_id_metadata
  projects_id_metadata : - could be a separate page 
  projects_id_metadata : - view all (meta)data in project
  projects_id_metadata : - link to create (meta)data in project
  projects_id_metadata : - link to update (meta)data in project
  projects_id_metadata : - link to delete (meta)data in project

  state "<&plus> projects <id> metadata create" as projects_id_metadata_create
  projects_id_metadata_create : - could be a separate page 
  projects_id_metadata_create : - write in name
  projects_id_metadata_create : - write in description
  projects_id_metadata_create : - create id for metadata
  projects_id_metadata_create : - get metadata on data file's columns
  projects_id_metadata_create : - update a column's name
  projects_id_metadata_create : - update a column's description
  projects_id_metadata_create : - update a column's detailed description?
  projects_id_metadata_create : - update a column's data type
  projects_id_metadata_create : - exclude a column from being stored
  projects_id_metadata_create : - save progress
  projects_id_metadata_create : - create database of data file
  projects_id_metadata_create : - check for problems in data 
  projects_id_metadata_create : - inform user of problems in data 
  projects_id_metadata_create : - provide a file with a list of problems
  projects_id_metadata_create : - finish metadata creation
  projects_id_metadata_create : - link to view newly created (meta)data 

  state "<&magnifying-glass> projects <id> metadata <id>" as projects_id_metadata_id
  projects_id_metadata_id : - could be a separate page 
  projects_id_metadata_id : - view description
  projects_id_metadata_id : - view details of columns
  projects_id_metadata_id : - link to update metadata
  projects_id_metadata_id : - delete metadata

  state "<&pencil> projects <id> metadata <id> update" as projects_id_metadata_id_update
  projects_id_metadata_id_update : - could be a separate page 
  projects_id_metadata_id_update : - update description
  projects_id_metadata_id_update : - update column name
  projects_id_metadata_id_update : - update column description
  projects_id_metadata_id_update : - update column detailed description?
  projects_id_metadata_id_update : - save progress

  state "<&trash> projects <id> metadata <id> delete" as projects_id_metadata_id_delete
  projects_id_metadata_id_delete : - could be a button only
  projects_id_metadata_id_delete : - delete all contents of (meta)data
}

state "Data functionality" as group_data {
  state "<&pencil> projects <id> metadata <id> data update" as projects_id_metadata_id_data_update
  projects_id_metadata_id_data_update : - could be a separate page
  projects_id_metadata_id_data_update : - upload new data to existing data
  projects_id_metadata_id_data_update : - verify against metadata
  projects_id_metadata_id_data_update : - check for problems in the data
  projects_id_metadata_id_data_update : - inform user of problems in data
  projects_id_metadata_id_data_update : - provide a file with a list of problems
  projects_id_metadata_id_data_update : - merge new data with existing data

  state "<&trash> projects <id> metadata <id> data delete" as projects_id_metadata_id_data_delete
  projects_id_metadata_id_data_delete : - could be a button only
  projects_id_metadata_id_data_delete : - delete all contents of the data
}

' To get proper alignment
group_projects --[hidden]> group_data
group_metadata --[hidden]> group_data

projects -> projects_create
projects_create --> projects_id
projects --> projects_id

projects_id -> projects_id_update
projects_id -> projects_id_delete
projects_id --> projects_id_metadata

projects_id_metadata -> projects_id_metadata_create
projects_id_metadata --> projects_id_metadata_id

projects_id_metadata_create --> projects_id_metadata_id

projects_id_metadata_id -> projects_id_metadata_id_update
projects_id_metadata_id -> projects_id_metadata_id_delete

projects_id_metadata_id --> projects_id_metadata_id_data_update
projects_id_metadata_id --> projects_id_metadata_id_data_delete
@enduml
