@startuml schema-creation-sequence

' TODO: Need to update this

title Schema Creation (Preparation for Data Upload)

participant "User" as u
participant "Front end" as f
participant "API" as api
participant "Backend" as b

u -> f: User selects option to "Upload data"
f -> u: System shows data entry UI
u -> f: User selects the file (csv) to upload\nand clicks "Create New Schema"
f -> api: System transfers file to API
api -> api: System extracts headers and analyse data types
api -> api: System validates schema (missing definitions* in BLUE) 
api -> f: System transfers extracted headers and definitions*
f -> u: System shows headers and definitions* to user
note right of u
    Descriptions will always be missing from
    definitions* initially, since they are not
    in the file (but something that the user needs
    to add manually)
end note
u -> f: User completes and/or edits definitions*
f -> api: User clicks "Save and Submit"
api -> api: System validates schema\n(checks for missing fields definitions*)
group Validation error (missing definitions*)
    api --> f: System sends back error (missing definitions* in RED)
    f --> u: System shows headers and definitions* to user
    u --> f: User completes and/or edits definitions* again
    f --> api: User clicks "Save and Submit" again
    api --> api: System validates schema again\n(checks for missing fields definitions*)
end
group Validation success (no missing definitions*)
    api -> b: System posts schema with "Completed" flag
    b -> b : System creates record\nand logs data changes
    b -> api: System confirms created schema
    api -> f: System retrieves confirmation
    f -> u: System displays confirmation
end
footer \n*Definitions include a header (variable name), data type, description (sentence describing what's in the variable), NULL/not NULL, and an optional title (reader friendly variable name)\nExample:\nHeader = "adr1",\ndata type = varchar,\ndescription = "first address line of patient's address",\ntitle (optional): "address line 1"

@enduml