@startuml user-flow-table-metadata-creation

title User Flow: Table Metadata Creation

'copied from user-flow.puml start
'table metadata creation start
  :User selects\n"Create New Table";
  :System shows overlay where user will define table name and description;
  :User fills out table name and description and clicks "Create";
  while (\nVALIDATION CHECK: Does table with this name already exist?\n) is (Yes)
    :System shows error message:
    "Table with this name already
    exists. Please rename your table.";
    :User renames table; 
  end while (No)
'table metadata creation end
'copied from user-flow.puml end
:...;

@enduml
