@startuml user-flow-table-created-continue-to-upload

title User Flow: Table created - Continue to Upload?

:...;
:User clicks "Save and Submit Table";
#palegreen:System confirms: "New Table added Successfully";
if (System asks user if they want to upload data) then (No)
  :User "quits" Sprout; 
  end
else (Yes)
  :User clicks "Continue to Data Upload";
endif
:...;

@enduml
