@startuml user-flow-schema-creation

title User Flow: Schema Creation

:User selects option to "Upload Data";
if (\nSystem shows data upload\nUI with option to create new\nschema or use existing one\n) then (Create New Schema)
  :User selects\n"Create New Schema";
switch (System shows create schema UI)
case (Create Schema\nfrom File)
  :User selects
  "Create Schema
  from File";
  :System shows UI
  with file upload;
  :User selects file and
  clicks "Create Schema";
  :System loads file and
  attempts to extract 
  headers and definitions*;
case (Create Schema from\nExisting Schema)
  :User selects
  "Create New Schema
  from Existing Schema";
  :System shows list of
  existing schemas;
  :User inspects schemas
  and selects base schema;
case (Create Schema Manually)
  :User selects
  "Create Schema Manually";
  :System shows UI where
  user can create schema manually;
  :User adds headers
  and definitions;
  :User clicks "Save
  and Submit Schema";
endswitch
#palegreen:Initial schema has been created;
:...;
detach
else (Use Existing Schema)
  :...;
  detach
endif

footer \n*Definition includes the header (column name), data type, description (sentence describing what is in the variable),\nis-nullable (boolean), and an optional title (reader friendly column name).\nExample:\nHeader = "adr1",\ndata type = varchar,\ndescription = "first address line of patient's address",\nisNULLABLE = 0, \ntitle (optional): "address line 1"
@enduml
