@startuml user-flow-column-metadata-creation

title User Flow: Column Metadata Creation

:...;
'copied from user-flow.puml start
'column metadata creation start
  switch (System shows create table UI)
    case (Create Column Metadata\nfrom File with Data)
      :User selects
      "Create Column Metadata
      from Data File";
      :System shows UI
      with file upload;
      :User selects file and
      clicks "Extract Data Structure";
      :System loads file and
      extracts column metadata*;
    while (\nVALIDATION CHECK: Is file a CSV?\n) is (No)
      :System shows error message: 
      "The file is not a CSV. Please
      choose a CSV to extract table
      metadata from";
      :User selects new file to upload;
    end while (Yes)
    :System extracts column
    metadata from File with Data;
    case (Create Column Metadata from \nFile with Column Metadata)
      :User selects "Create Column Metadata
      from File with Metadata";
      :System shows UI with
      file upload;
      :User selects file with
      metadata and clicks 
      "Extract Data Structure";
      :System extracts column metadata from file;
    case (Create Table from\nExisting Table)
      :User selects
      "Create New Table
      from Existing Table";
      :System shows list of
      existing tables;
      :User inspects tables
      and selects base table;
    case (Create Table Manually)
      :User selects
      "Create Table Manually";
      :System shows UI where
      user can create table manually;
      :User adds table metadata;
      :User clicks "Submit";
    endswitch
'validation table completeness start
    :System shows UI where user can 
    add/edit the following fields:
    - Column name (textbox)
    - Title (textbox, optional)
    - Data type (dropdown)
    - Short description (textbox)
    - Allow missing (boolean) 
    - Allow duplication (boolean)
    :Use completes/edits table
    and clicks "Submit";
'column metadata creation end
'copied from user-flow.puml end

@enduml
