@startuml create-resource-properties
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main

state "Input" as input {
  input : - `path_*()` functions assist with giving correct paths
' Arguments -----
  path : - Path to resource <id> folder
  properties: - JSON object of the resource\n  following the Data Package spec
}

state "Output" as output {
  state "JSON" as json_output
  json_output : - JSON object of the resource following\n  the Data Package spec
  json_output : - Use `write_resource_properties()` to\n  save back to `datapackage.json`
}

state "create_resource_properties()" as crp {
  crp : - Required arg: path and properties object

  state arg_path <<entryPoint>>
  state arg_properties <<entryPoint>>

  path --> arg_path
  properties --> arg_properties

  state "verify_is_dir()" as vid
  vid : - Required arg: path
  vid : - Output: path or Error
  arg_path --> vid : path object

  state "create_relative_resource_data_path()" as crrdp
  crrdp : - Required arg: absolute path from input
  crrdp : - Output: relative path\n  (e.g. `resources/1/data.parquet`)
  vid --> crrdp : path object

  state "verify_resource_properties()" as vrp
  vrp : - Required arg: properties
  vrp : - Output: JSON or Error
  vrp : - Checks against spec
  arg_properties --> vrp : JSON object

  state "edit_resource_properties_field()" as erpf
  erpf : - Required args: properties, field, value
  erpf : - Output: JSON
  crrdp --> erpf : Update `path`\nproperty
  vrp --> erpf : JSON object

  state "return" <<exitPoint>>
  erpf --> return : JSON object
  return --> output
}
@enduml

